return {
  {
    "nvim-treesitter/nvim-treesitter",
    branch = 'master',
    lazy = false,
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        highlight = { enable = true },
        indent = { enable = true },
        ensure_installed = {
          "astro",
          "bash",
          "c",
          "cpp",
          "css",
          "dockerfile",
          "gleam",
          "hcl",
          "html",
          "javascript",
          "jsdoc",
          "json",
          "json5",
          "jsonc",
          "lua",
          "luadoc",
          "luap",
          "markdown",
          "markdown_inline",
          "nix",
          "nu",
          "python",
          "query",
          "regex",
          "rust",
          "go",
          "svelte",
          "toml",
          "tsx",
          "typescript",
          "vue",
          "vim",
          "vimdoc",
          "yaml",
          "wgsl",
          "sql",
        },
      })
    end,
  },
}
